import { TopologyConfig, TopologyKey } from '../types/converter';

export const TOPOLOGIES: Record<TopologyKey, TopologyConfig> = {
  'dbr,fw,1p': {
    key: 'dbr,fw,1p',
    type: 'dbr',
    rectification: 'fw',
    phases: 1,
    title: 'DBR — Full Wave — 1 Phase',
    fullName: 'Single-Phase Diode Bridge Rectifier (Full-Wave)',
    deviceType: 'diode',
    devicePrefix: 'D',
    devices: ['D1', 'D2', 'D3', 'D4'],
    pulseCount: 2,
    description: 'A 4-diode full-bridge converter rectifying single-phase AC to DC. D1-D2 conduct during the positive half-cycle, and D3-D4 conduct during the negative half-cycle.',
    theoreticalFormula: 'V_{dc} = \\frac{2 V_m}{\\pi} \\approx 0.6366 \\cdot V_m'
  },
  'dbr,hw,1p': {
    key: 'dbr,hw,1p',
    type: 'dbr',
    rectification: 'hw',
    phases: 1,
    title: 'DBR — Half Wave — 1 Phase',
    fullName: 'Single-Phase Diode Half-Wave Rectifier',
    deviceType: 'diode',
    devicePrefix: 'D',
    devices: ['D1'],
    pulseCount: 1,
    description: 'A single diode in series with the AC source and RL load. Conducts only during the positive half-cycle and freewheels into the negative region due to inductive stored energy.',
    theoreticalFormula: 'V_{dc} = \\frac{V_m}{2\\pi}(1 - \\cos\\beta) \\quad [\\text{R load: } \\frac{V_m}{\\pi} \\approx 0.3183 \\cdot V_m]'
  },
  'dbr,fw,3p': {
    key: 'dbr,fw,3p',
    type: 'dbr',
    rectification: 'fw',
    phases: 3,
    title: 'DBR — Full Wave — 3 Phase',
    fullName: 'Three-Phase 6-Pulse Diode Bridge Rectifier',
    deviceType: 'diode',
    devicePrefix: 'D',
    devices: ['D1', 'D2', 'D3', 'D4', 'D5', 'D6'],
    pulseCount: 6,
    description: 'A 6-diode three-phase bridge rectifier providing low ripple 6-pulse DC output. Conduction commutates naturally every 60° between diode pairs based on instantaneous line voltages.',
    theoreticalFormula: 'V_{dc} = \\frac{3\\sqrt{3} V_{m,ph}}{\\pi} = \\frac{3 V_{m,LL}}{\\pi} \\approx 1.654 \\cdot V_{m,ph}'
  },
  'dbr,hw,3p': {
    key: 'dbr,hw,3p',
    type: 'dbr',
    rectification: 'hw',
    phases: 3,
    title: 'DBR — Half Wave — 3 Phase',
    fullName: 'Three-Phase 3-Pulse Diode Rectifier (Star/Neutral Return)',
    deviceType: 'diode',
    devicePrefix: 'D',
    devices: ['D1', 'D2', 'D3'],
    pulseCount: 3,
    description: 'A 3-diode half-wave star-connected converter with neutral return. Each diode conducts for 120° during the period when its phase voltage is the most positive.',
    theoreticalFormula: 'V_{dc} = \\frac{3\\sqrt{3} V_{m,ph}}{2\\pi} \\approx 0.827 \\cdot V_{m,ph}'
  },
  'tcr,fw,1p': {
    key: 'tcr,fw,1p',
    type: 'tcr',
    rectification: 'fw',
    phases: 1,
    title: 'TCR — Full Wave — 1 Phase',
    fullName: 'Single-Phase Controlled Thyristor Bridge Rectifier',
    deviceType: 'thyristor',
    devicePrefix: 'T',
    devices: ['T1', 'T2', 'T3', 'T4'],
    pulseCount: 2,
    description: 'A fully-controlled 4-SCR bridge. Thyristor pair (T1, T2) is fired at α, and pair (T3, T4) is fired at 180° + α. Allows continuous DC voltage control and inversion.',
    theoreticalFormula: 'V_{dc} = \\frac{2 V_m}{\\pi} \\cos\\alpha \\quad [\\text{CCM}]'
  },
  'tcr,hw,1p': {
    key: 'tcr,hw,1p',
    type: 'tcr',
    rectification: 'hw',
    phases: 1,
    title: 'TCR — Half Wave — 1 Phase',
    fullName: 'Single-Phase Controlled Thyristor Half-Wave Converter',
    deviceType: 'thyristor',
    devicePrefix: 'T',
    devices: ['T1'],
    pulseCount: 1,
    description: 'A single thyristor triggered at delay angle α. Conduction begins at α and extinguishes when current drops to zero at extinction angle β > 180° due to load inductance.',
    theoreticalFormula: 'V_{dc} = \\frac{V_m}{2\\pi}(\\cos\\alpha - \\cos\\beta) \\quad [\\text{R load: } \\frac{V_m}{2\\pi}(1 + \\cos\\alpha)]'
  },
  'tcr,fw,3p': {
    key: 'tcr,fw,3p',
    type: 'tcr',
    rectification: 'fw',
    phases: 3,
    title: 'TCR — Full Wave — 3 Phase',
    fullName: 'Three-Phase 6-Pulse Fully-Controlled Thyristor Bridge',
    deviceType: 'thyristor',
    devicePrefix: 'T',
    devices: ['T1', 'T2', 'T3', 'T4', 'T5', 'T6'],
    pulseCount: 6,
    description: 'The standard industrial 6-SCR converter bridge. Gate pulses are synchronized to 3-phase AC with firing delay α referenced from natural commutation at 30°.',
    theoreticalFormula: 'V_{dc} = \\frac{3\\sqrt{3} V_{m,ph}}{\\pi} \\cos\\alpha = \\frac{3 V_{m,LL}}{\\pi} \\cos\\alpha \\quad [\\text{CCM}]'
  },
  'tcr,hw,3p': {
    key: 'tcr,hw,3p',
    type: 'tcr',
    rectification: 'hw',
    phases: 3,
    title: 'TCR — Half Wave — 3 Phase',
    fullName: 'Three-Phase 3-Pulse Controlled Thyristor Converter',
    deviceType: 'thyristor',
    devicePrefix: 'T',
    devices: ['T1', 'T2', 'T3'],
    pulseCount: 3,
    description: 'A 3-SCR star converter with neutral return. Thyristors T1, T2, T3 are triggered sequentially at (30° + α), (150° + α), (270° + α).',
    theoreticalFormula: 'V_{dc} = \\frac{3\\sqrt{3} V_{m,ph}}{2\\pi} \\cos\\alpha \\quad [\\text{for } \\alpha \\le 30^\\circ \\text{ or CCM}]'
  }
};
